<a href="https://colab.research.google.com/github/Prudhvisankar2002/Python-Libraries/blob/main/labraries_funtion_add_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Add values into array values?
import numpy as np
m1=[[76,56,89],[34,44,76],[23,67,55]]
data=np.array(m1)
print(data + 20)

[[ 96  76 109]
 [ 54  64  96]
 [ 43  87  75]]


In [ ]:
#Add two tables using numpy function?
import numpy as np
m1=[[76,56,89],[34,44,76],[23,67,55]]
m2=[[55,85,96],[22,33,44],[74,85,20]]

print(m1)
print()
print(m2)
print()
print(np.add(m1,m2))

[[76, 56, 89], [34, 44, 76], [23, 67, 55]]

[[55, 85, 96], [22, 33, 44], [74, 85, 20]]

[[152 112 178]
 [ 68  88 152]
 [ 46 134 110]]


In [ ]:
#Subtract two tables using numpy function?
import numpy as np
m1=[[76,56,89],[34,44,76],[23,67,55]]
m2=[[55,85,96],[22,33,44],[74,85,20]]

print(m1)
print()
print(m2)
print()
print(np.subtract(m1,m2))

[[76, 56, 89], [34, 44, 76], [23, 67, 55]]

[[55, 85, 96], [22, 33, 44], [74, 85, 20]]

[[ 21 -29  -7]
 [ 12  11  32]
 [-51 -18  35]]


In [ ]:
#write the zeros() function in numpy Array?
import numpy as np
sales=np.zeros(5)
print('sales converts into zeros:',sales)

sales converts into zeros: [0. 0. 0. 0. 0.]


In [ ]:
#write the ones() function in numpy Array?
import numpy as np
buys=np.ones(10)
print('buys converts into ones:',buys)

buys converts into ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [10]:
#Write a program for count_nonzero() funtion?

import numpy as np
m1=[[76,0,89],[34,0,76],[0,67,55]]   #-->Here total 9 values
c=np.count_nonzero(m1)
print('count of non zero vales in the m1_data:-',c)   #total values 9 and zeros 3 --> 9-3=(6)


count of non zero vales in the m1_data:- 6
