<a href="https://colab.research.google.com/github/Prudhvisankar2002/Python-Libraries/blob/main/methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
  # numpy on methods

  #//methods are predefined methods

  #They are:-sum(),min(),max(),sort(),reshape(),flatend(),trace()

In [12]:
import numpy as np                                         #SUM()-->methode
data=[[12,23,45],[11,56,90],[55,67,45]]
find=np.array(data)
print(find)
print()
print('Total sum of the data is:',find.sum())

[[12 23 45]
 [11 56 90]
 [55 67 45]]

Total sum of the data is: 404


In [13]:
import numpy as np                                         #MIN()-->methode
data=[[12,23,45],[11,56,90],[55,67,45]]
find=np.array(data)
print(find)
print()
print('minimum value of the data is:',find.min())

[[12 23 45]
 [11 56 90]
 [55 67 45]]

minimum value of the data is: 11


In [14]:
import numpy as np                                         #max()-->methode
data=[[12,23,45],[11,56,90],[55,67,45]]
find=np.array(data)
print(find)
print()
print('maximum value of the data is:',find.max())

[[12 23 45]
 [11 56 90]
 [55 67 45]]

maximum value of the data is: 90


In [18]:
import numpy as np                                         #RESHAPE()-->methode
data=[[12,23,45],[11,56,90],[55,67,45],[38,25,78]]                    #reshape() used enter with parameter inside the paranthasis()
find=np.array(data)
print(find)
print()
print('Reshape of the data is:',find.reshape(6,2))

[[12 23 45]
 [11 56 90]
 [55 67 45]
 [38 25 78]]

Reshape of the data is: [[12 23]
 [45 11]
 [56 90]
 [55 67]
 [45 38]
 [25 78]]


In [38]:
import numpy as np                                         #SORT()-->methode
data=[[55,23,5],[11,10,7],[55,67,45]]
find=np.array(data)
print(find)
print()
a = find.sort()
print(a)

[[55 23  5]
 [11 10  7]
 [55 67 45]]

None


In [1]:
import numpy as np                                         #FLATTEN()-->methode
data=[[12,23,45],[11,56,90],[55,67,45]]
find=np.array(data)
print(find)
print()
print('data change into one dimension:',find.flatten())

[[12 23 45]
 [11 56 90]
 [55 67 45]]

data change into one dimension: [12 23 45 11 56 90 55 67 45]


In [4]:
import numpy as np                                         #trace()-->methode
data=[[12,23,45],[11,56,90],[55,67,45]]
find=np.array(data)
print(find)
print()
print('diagonals of the data is:',find.diagonal())
print()
print('diagonal sum is:',find.trace())

[[12 23 45]
 [11 56 90]
 [55 67 45]]

diagonals of the data is: [12 56 45]

diagonal sum is: 113
